model_name: 'dcgan'
dataset: 'svhn'
dataset_dir: '$ROOT/data/'
log_folder: '$ROOT/logs/'
save_path: '$ROOT/checkpoints/dcgan_svhn/'
plot_folder: '$ROOT/debug_plot/dcgan_svhn/'
max_epochs: 1
batch_size: 256
num_workers: 4
plot_interval: 100
learning_rate: 1e-3
beta1: 0.5
beta2: 0.999
random_seed: 1